name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  storybook7:
    runs-on: ubuntu-latest
    env:
      HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
      HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build && yarn happo run
      - run: HAPPO_USE_PREBUILT_PACKAGE=yes yarn build-local-storybook && yarn happo run

  storybook6:
    runs-on: ubuntu-latest
    env:
      HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
      HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn add @storybook/core@6 @storybook/addons@6 @storybook/react@6 @storybook/addon-actions@6 @storybook/api@6 @storybook/addon-interactions@6 storybook@6 --dev
      - run: yarn remove @storybook/react-webpack5
      - run: DISABLE_REACT_WEBPACK5_FRAMEWORK=true yarn build && yarn happo run

  storybook5:
    runs-on: ubuntu-latest
    env:
      HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
      HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: echo "import '../register'; export default {};" > .storybook/config.js
      - run: rm .storybook/preview.js
      - run: yarn add @storybook/core@5 @storybook/addons@5 @storybook/react@5 @storybook/addon-actions@5 @storybook/api@5 @storybook/addon-interactions@5 storybook@5 --dev
      - run: yarn remove @storybook/react-webpack5
      - run: USE_STORYSTORE_V7=false DISABLE_REACT_WEBPACK5_FRAMEWORK=true yarn build && yarn happo run
