name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  storybook8:
    runs-on: ubuntu-latest
    env:
      HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
      HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
      HAPPO_PROJECT: storybook8

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: npx -p happo.io happo-ci-github-actions
      - run: yarn build-local-storybook && HAPPO_USE_PREBUILT_PACKAGE=yes HAPPO_PROJECT=storybook8-prebuilt npx -p happo.io happo-ci-github-actions

  storybook7:
    runs-on: ubuntu-latest
    env:
      HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
      HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
      HAPPO_PROJECT: storybook7

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn add --dev @storybook/addon-actions@7 @storybook/addon-interactions@7 @storybook/api@7 @storybook/manager-api@7 @storybook/preview-api@7 @storybook/react@7 @storybook/react-webpack5@7 storybook@7 @storybook/test@7
      - run: yarn build && npx -p happo.io happo-ci-github-actions

  storybook6:
    runs-on: ubuntu-latest
    env:
      HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
      HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
      DISABLE_REACT_WEBPACK5_FRAMEWORK: true
      DISABLE_ADDONS: true
      HAPPO_DEBUG: true
      HAPPO_PROJECT: storybook6

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: rm .storybook/Interactive.stories.js
      - run: mv .storybook/preview-storybook-6.js .storybook/preview.js
      - run: yarn add --dev storybook@6 @storybook/addon-actions@6 @storybook/addon-interactions@6 @storybook/api@6 @storybook/react@6 global @storybook/channels@6 @storybook/channel-websocket@6
      - run: yarn build
      - run: yarn storybook build --version
      - run: npx -p happo.io happo-ci-github-actions

  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Start dev server and run tests
        run: |
          yarn dev & # Start dev server in background
          sleep 5 # Wait for server to be ready
          yarn playwright test
